config/routes.rb
CashTodoList::Application.routes.draw do
  devise_for :users

  resources :tasks
  resources :cycles  
  resources :users

  root :to => "tasks#index"

  

end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
	belongs_to :user
	has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :cycle
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cycles

  def active_cycle
  	self.cycles.first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #User auth
  before_filter :authenticate_user!  
end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController
  before_action :set_cycle, only: [:show, :edit, :update, :destroy]

  # GET /cycles
  # GET /cycles.json
  def index
    @cycles = Cycle.all
  end

  # GET /cycles/1
  # GET /cycles/1.json
  def show
  end

  # GET /cycles/new
  def new
    @cycle = Cycle.new
  end

  # GET /cycles/1/edit
  def edit
  end

  # POST /cycles
  # POST /cycles.json
  def create
    @cycle = Cycle.new(cycle_params)

    #Set actual_cash equal to initial_cash
    @cycle.actual_cash = @cycle.initial_cash

    #Set paid to false
    @cycle.paid = false

    #Set user to current_user
    @cycle.user = current_user

    respond_to do |format|
      if @cycle.save
        format.html { redirect_to @cycle, notice: 'Cycle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cycle }
      else
        format.html { render action: 'new' }
        format.json { render json: @cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cycles/1
  # PATCH/PUT /cycles/1.json
  def update
    respond_to do |format|
      if @cycle.update(cycle_params)
        format.html { redirect_to @cycle, notice: 'Cycle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cycles/1
  # DELETE /cycles/1.json
  def destroy
    @cycle.destroy
    respond_to do |format|
      format.html { redirect_to cycles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cycle
      @cycle = Cycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cycle_params
      params.require(:cycle).permit(:initial_cash, :actual_cash, :paid)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    #Set cycle
    @task.cycle = current_user.active_cycle

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :deadline, :importance, :success)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:red, :yellow, :blue, :gray)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cycles/_form.html.erb
<%= form_for @cycle, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :initial_cash, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :initial_cash, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :actual_cash, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :actual_cash, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :paid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :paid, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cycles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/cycles/edit.html.erb
<%- model_class = Cycle -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cycles/index.html.erb
<%- model_class = Cycle -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:initial_cash) %></th>
      <th><%= model_class.human_attribute_name(:actual_cash) %></th>
      <th><%= model_class.human_attribute_name(:paid) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cycles.each do |cycle| %>
      <tr>
        <td><%= link_to cycle.id, cycle_path(cycle) %></td>
        <td><%= cycle.initial_cash %></td>
        <td><%= cycle.actual_cash %></td>
        <td><%= cycle.paid %></td>
        <td><%= cycle.user_id %></td>
        <td><%=l cycle.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cycle_path(cycle), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cycle_path(cycle),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cycle_path,
            :class => 'btn btn-primary' %>

app/views/cycles/new.html.erb
<%- model_class = Cycle -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cycles/show.html.erb
<%- model_class = Cycle -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:initial_cash) %>:</strong></dt>
  <dd><%= @cycle.initial_cash %></dd>
  <dt><strong><%= model_class.human_attribute_name(:actual_cash) %>:</strong></dt>
  <dd><%= @cycle.actual_cash %></dd>
  <dt><strong><%= model_class.human_attribute_name(:paid) %>:</strong></dt>
  <dd><%= @cycle.paid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @cycle.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cycles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cycle_path(@cycle), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cycle_path(@cycle),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CashTodoList" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "CashTodoList" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
       	    <ul class="nav">
                <a class="brand" href="#">CashTodoList</a>
                <li><%= link_to 'Tasks', tasks_path %></li>        		
                <li><%= link_to 'Preferences', edit_user_path(current_user) %></li>
                <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
     	      </ul>
          </div>
        </div>     
      </div>
      
      <div class="container container-fluid main-container">        
          
          <div class="row row-fluid">
            <div class="span12">              
              <%= yield %>
            </div>
          </div>          
        
      </div>

   </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :deadline, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :deadline, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :importance, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :importance, :class => 'text_field' %>
    </div>
  </div>  

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table">
  <tbody>
    <% current_user.active_cycle.tasks.each do |task| %>
      <tr>
        <td><%= link_to task.description, task_path(task) %></td>        
        <td><%= task.deadline %></td>
        <td><%= task.importance %></td>
        <td><%= task.success %></td>        
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_task_path(task), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      task_path(task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_task_path,
            :class => 'btn btn-primary' %>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @task.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deadline) %>:</strong></dt>
  <dd><%= @task.deadline %></dd>
  <dt><strong><%= model_class.human_attribute_name(:importance) %>:</strong></dt>
  <dd><%= @task.importance %></dd>
  <dt><strong><%= model_class.human_attribute_name(:success) %>:</strong></dt>
  <dd><%= @task.success %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cycle_id) %>:</strong></dt>
  <dd><%= @task.cycle_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tasks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :red, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :red, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :yellow, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :yellow, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :blue, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :blue, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gray, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :gray, :class => 'text_field' %>
    </div>
  </div>
  <!--<div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :encrypted_password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :encrypted_password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_token, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_token, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_sent_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :remember_created_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :remember_created_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>-->

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <!--<h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>-->
  <h1>Preferences</h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:red) %></th>
      <th><%= model_class.human_attribute_name(:yellow) %></th>
      <th><%= model_class.human_attribute_name(:blue) %></th>
      <th><%= model_class.human_attribute_name(:gray) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.red %></td>
        <td><%= user.yellow %></td>
        <td><%= user.blue %></td>
        <td><%= user.gray %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:red) %>:</strong></dt>
  <dd><%= @user.red %></dd>
  <dt><strong><%= model_class.human_attribute_name(:yellow) %>:</strong></dt>
  <dd><%= @user.yellow %></dd>
  <dt><strong><%= model_class.human_attribute_name(:blue) %>:</strong></dt>
  <dd><%= @user.blue %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gray) %>:</strong></dt>
  <dd><%= @user.gray %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>